language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - npm install -g less
  - npm install -g cssmin
  - npm install -g uglify-js
  - composer install

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml